import { INestApplication, ValidationPipe } from '@nestjs/common';
import { Test, TestingModule } from '@nestjs/testing';
import * as request from 'supertest';

import { ActionType } from '../../../domain/entities/action-type.entity';
import { UUID, PaginatedResult } from '../../../domain/shared/types/common';
import { ActionTypeName } from '../../../domain/value-objects/action-type-name';
import { PaginatedResponseDto } from '../../../infrastructure/dto/paginated-response.dto';
import {
  NotFoundError,
  ConflictError,
  ValidationException,
} from '../../../infrastructure/exceptions/app.exceptions';
import { GlobalExceptionFilter } from '../../../infrastructure/filters/global-exception.filter';
import {
  CreateActionTypeData,
  UpdateActionTypeData,
  ActionTypeFilterOptions,
  ActionTypeStats,
  IActionTypesRepository,
} from '../../interfaces/action-types-repository.interface';
import { ActionTypesService } from '../../services/action-types.service';
import { ActionTypesController } from '../action-types.controller';

// Mock service
const mockActionTypesService = {
  create: jest.fn(),
  findAll: jest.fn(),
  findByHabitId: jest.fn(),
  findOne: jest.fn(),
  update: jest.fn(),
  remove: jest.fn(),
  findMostActive: jest.fn(),
  findRecentlyActive: jest.fn(),
  getStatsByHabitId: jest.fn(),
};

/**
 * ActionTypesController Test Suite
 *
 * DTO Structure Guidelines:
 * ========================
 *
 * CreateActionTypeDto (REQUEST):
 * - Contains ONLY domain fields: name, habitId
 * - File upload (logo) handled separately via multipart/form-data
 * - Database-generated fields are NEVER in request DTOs
 * - Validation pipe with whitelist:true strips any extra fields
 *
 * Database-generated fields (NEVER in requests):
 * - id (UUID - generated by database)
 * - createdAt (timestamp - generated by database)
 * - updatedAt (timestamp - generated by database)
 * - lastActionDate (nullable timestamp - managed by application logic)
 * - totalActionsCount (integer - managed by application logic)
 *
 * Response Structure:
 * - Service returns complete entity WITH all database-generated fields
 * - Response includes: id, name, logo, habitId, totalActionsCount, lastActionDate, createdAt, updatedAt
 * - This is correct because responses reflect the persisted state
 */
describe('ActionTypesController (RED PHASE)', () => {
  let app: INestApplication;
  let actionTypesService: jest.Mocked<ActionTypesService>;

  // Test data fixtures
  const mockActionTypeId: UUID = '123e4567-e89b-12d3-a456-426614174000';
  const mockHabitId: UUID = '987fcdeb-51a2-43d1-9876-543210987654';
  const mockActionTypeName = 'Morning Push-ups';
  const mockLogo = 'https://example.com/pushups-logo.png';
  const fixedDate = new Date('2024-01-01T00:00:00.000Z');

  const createMockActionTypeResponse = (overrides: Partial<any> = {}) => ({
    id: mockActionTypeId,
    name: mockActionTypeName,
    logo: mockLogo,
    habitId: mockHabitId,
    totalActionsCount: 0,
    lastActionDate: null,
    createdAt: fixedDate,
    updatedAt: fixedDate,
    ...overrides,
  });

  const createMockFile = () => {
    const buffer = Buffer.from('fake image data');
    return {
      fieldname: 'logo',
      originalname: 'test-logo.png',
      encoding: '7bit',
      mimetype: 'image/png',
      size: buffer.length,
      buffer,
    };
  };

  beforeAll(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      controllers: [ActionTypesController],
      providers: [
        {
          provide: ActionTypesService,
          useValue: mockActionTypesService,
        },
      ],
    }).compile();

    app = moduleFixture.createNestApplication();

    // Add validation pipe and global exception filter
    app.useGlobalPipes(new ValidationPipe({ transform: true, whitelist: true }));
    app.useGlobalFilters(new GlobalExceptionFilter());

    actionTypesService = app.get(ActionTypesService);

    await app.init();
  });

  afterAll(async () => {
    await app.close();
  });

  beforeEach(() => {
    jest.clearAllMocks();
  });

  describe('POST /action-types', () => {
    // CreateActionTypeDto contains ONLY domain fields: name and habitId
    // File upload (logo) is handled separately via multipart/form-data
    const createActionTypeDto = {
      name: mockActionTypeName,
      habitId: mockHabitId,
    };

    it('should create a new action type with file upload', async () => {
      // Arrange
      // Response includes complete entity with database-generated fields
      const expectedResponse = createMockActionTypeResponse();
      mockActionTypesService.create.mockResolvedValue(expectedResponse);

      // Act & Assert
      const response = await request(app.getHttpServer())
        .post('/action-types')
        .field('name', createActionTypeDto.name)
        .field('habitId', createActionTypeDto.habitId)
        .attach('logo', createMockFile().buffer, 'test-logo.png')
        .expect(201);

      // Response should include complete entity with database-generated fields
      expect(response.body).toEqual(expectedResponse);
      expect(response.body).toHaveProperty('id');
      expect(response.body).toHaveProperty('createdAt');
      expect(response.body).toHaveProperty('updatedAt');
      expect(response.body).toHaveProperty('totalActionsCount');
      expect(response.body).toHaveProperty('lastActionDate');

      // Service should be called with only domain fields (name, habitId) and file
      expect(mockActionTypesService.create).toHaveBeenCalledWith(
        createActionTypeDto,
        expect.objectContaining({
          originalname: 'test-logo.png',
          mimetype: 'image/png',
        })
      );
    });

    // Validation tests for DOMAIN FIELDS ONLY (name, habitId)
    // Database-generated fields are NOT validated in requests - they should be stripped by whitelist

    it('should return 400 when name is missing', async () => {
      // Act & Assert - Validate required domain field: name
      await request(app.getHttpServer())
        .post('/action-types')
        .field('habitId', mockHabitId)
        .attach('logo', createMockFile().buffer, 'test-logo.png')
        .expect(400);

      expect(mockActionTypesService.create).not.toHaveBeenCalled();
    });

    it('should return 400 when habitId is missing', async () => {
      // Act & Assert - Validate required domain field: habitId
      await request(app.getHttpServer())
        .post('/action-types')
        .field('name', mockActionTypeName)
        .attach('logo', createMockFile().buffer, 'test-logo.png')
        .expect(400);

      expect(mockActionTypesService.create).not.toHaveBeenCalled();
    });

    it('should return 400 when logo file is missing', async () => {
      // Act & Assert - Validate required file upload: logo
      await request(app.getHttpServer())
        .post('/action-types')
        .field('name', createActionTypeDto.name)
        .field('habitId', createActionTypeDto.habitId)
        .expect(400);

      expect(mockActionTypesService.create).not.toHaveBeenCalled();
    });

    it('should return 400 when name is too short', async () => {
      // Act & Assert - Validate domain field constraint: name length (min 2)
      await request(app.getHttpServer())
        .post('/action-types')
        .field('name', 'A') // Too short
        .field('habitId', mockHabitId)
        .attach('logo', createMockFile().buffer, 'test-logo.png')
        .expect(400);

      expect(mockActionTypesService.create).not.toHaveBeenCalled();
    });

    it('should return 400 when name is too long', async () => {
      // Act & Assert - Validate domain field constraint: name length (max 100)
      await request(app.getHttpServer())
        .post('/action-types')
        .field('name', 'A'.repeat(101)) // Too long
        .field('habitId', mockHabitId)
        .attach('logo', createMockFile().buffer, 'test-logo.png')
        .expect(400);

      expect(mockActionTypesService.create).not.toHaveBeenCalled();
    });

    it('should return 400 when habitId is not a valid UUID', async () => {
      // Act & Assert - Validate domain field format: habitId must be UUID
      await request(app.getHttpServer())
        .post('/action-types')
        .field('name', mockActionTypeName)
        .field('habitId', 'invalid-uuid')
        .attach('logo', createMockFile().buffer, 'test-logo.png')
        .expect(400);

      expect(mockActionTypesService.create).not.toHaveBeenCalled();
    });

    it('should strip database-generated fields from request (whitelist validation)', async () => {
      // Arrange
      const expectedResponse = createMockActionTypeResponse();
      mockActionTypesService.create.mockResolvedValue(expectedResponse);

      // Act & Assert - Try to send database-generated fields
      await request(app.getHttpServer())
        .post('/action-types')
        .field('name', mockActionTypeName)
        .field('habitId', mockHabitId)
        .field('id', '00000000-0000-0000-0000-000000000000') // Should be stripped
        .field('createdAt', new Date().toISOString()) // Should be stripped
        .field('updatedAt', new Date().toISOString()) // Should be stripped
        .field('totalActionsCount', '999') // Should be stripped
        .field('lastActionDate', new Date().toISOString()) // Should be stripped
        .attach('logo', createMockFile().buffer, 'test-logo.png')
        .expect(201);

      // Service should only receive domain fields (name, habitId), not database-generated fields
      expect(mockActionTypesService.create).toHaveBeenCalledWith(
        {
          name: mockActionTypeName,
          habitId: mockHabitId,
          // Database-generated fields should NOT be present here
        },
        expect.objectContaining({
          originalname: 'test-logo.png',
          mimetype: 'image/png',
        })
      );

      // Verify the call does NOT include database-generated fields
      const callArgs = mockActionTypesService.create.mock.calls[0][0];
      expect(callArgs).not.toHaveProperty('id');
      expect(callArgs).not.toHaveProperty('createdAt');
      expect(callArgs).not.toHaveProperty('updatedAt');
      expect(callArgs).not.toHaveProperty('totalActionsCount');
      expect(callArgs).not.toHaveProperty('lastActionDate');
    });

    it('should return 409 when action type name already exists for habit', async () => {
      // Arrange
      const conflictError = new ConflictError(
        `ActionType with name '${mockActionTypeName}' already exists for this habit`
      );
      mockActionTypesService.create.mockRejectedValue(conflictError);

      // Act & Assert
      await request(app.getHttpServer())
        .post('/action-types')
        .field('name', createActionTypeDto.name)
        .field('habitId', createActionTypeDto.habitId)
        .attach('logo', createMockFile().buffer, 'test-logo.png')
        .expect(409);
    });

    it('should return 422 when image upload fails', async () => {
      // Arrange
      const validationError = new ValidationException('Invalid image format');
      mockActionTypesService.create.mockRejectedValue(validationError);

      // Act & Assert
      await request(app.getHttpServer())
        .post('/action-types')
        .field('name', createActionTypeDto.name)
        .field('habitId', createActionTypeDto.habitId)
        .attach('logo', createMockFile().buffer, 'test-logo.png')
        .expect(422);
    });

    it('should handle file size validation', async () => {
      // Act & Assert - File too large (over 5MB limit)
      const largeBuffer = Buffer.alloc(6 * 1024 * 1024); // 6MB
      await request(app.getHttpServer())
        .post('/action-types')
        .field('name', createActionTypeDto.name)
        .field('habitId', createActionTypeDto.habitId)
        .attach('logo', largeBuffer, 'large-logo.png')
        .expect(400);
    });

    it('should handle invalid file type', async () => {
      // Act & Assert
      await request(app.getHttpServer())
        .post('/action-types')
        .field('name', createActionTypeDto.name)
        .field('habitId', createActionTypeDto.habitId)
        .attach('logo', createMockFile().buffer, 'document.pdf')
        .expect(400);
    });
  });

  describe('GET /action-types', () => {
    it('should return paginated action types without filters', async () => {
      // Arrange
      const mockResponse = new PaginatedResponseDto([createMockActionTypeResponse()], 1, 1, 10, 1);
      mockActionTypesService.findAll.mockResolvedValue(mockResponse);

      // Act & Assert
      const response = await request(app.getHttpServer()).get('/action-types').expect(200);

      expect(response.body).toEqual({
        data: [createMockActionTypeResponse()],
        total: 1,
        page: 1,
        limit: 10,
        totalPages: 1,
      });
      expect(mockActionTypesService.findAll).toHaveBeenCalledWith(
        { page: 1, limit: 10 },
        undefined
      );
    });

    it('should handle pagination query parameters', async () => {
      // Arrange
      const mockResponse = new PaginatedResponseDto([], 0, 2, 5, 0);
      mockActionTypesService.findAll.mockResolvedValue(mockResponse);

      // Act & Assert
      await request(app.getHttpServer())
        .get('/action-types')
        .query({ page: '2', limit: '5' })
        .expect(200);

      expect(mockActionTypesService.findAll).toHaveBeenCalledWith({ page: 2, limit: 5 }, undefined);
    });

    it('should handle filter query parameters', async () => {
      // Arrange
      const mockResponse = new PaginatedResponseDto([], 0, 1, 10, 0);
      mockActionTypesService.findAll.mockResolvedValue(mockResponse);
      const filters: ActionTypeFilterOptions = {
        habitId: mockHabitId,
        hasActions: true,
      };

      // Act & Assert
      await request(app.getHttpServer())
        .get('/action-types')
        .query({
          habitId: mockHabitId,
          hasActions: 'true',
        })
        .expect(200);

      expect(mockActionTypesService.findAll).toHaveBeenCalledWith(
        { page: 1, limit: 10 },
        expect.objectContaining(filters)
      );
    });

    it('should validate pagination parameters', async () => {
      // Act & Assert
      await request(app.getHttpServer())
        .get('/action-types')
        .query({ page: '0', limit: '101' }) // Invalid values
        .expect(400);
    });

    it('should validate filter parameters', async () => {
      // Act & Assert
      await request(app.getHttpServer())
        .get('/action-types')
        .query({ habitId: 'invalid-uuid' })
        .expect(400);
    });
  });

  describe('GET /action-types/habit/:habitId', () => {
    it('should return action types for specific habit', async () => {
      // Arrange
      const mockResponse = new PaginatedResponseDto([createMockActionTypeResponse()], 1, 1, 10, 1);
      mockActionTypesService.findByHabitId.mockResolvedValue(mockResponse);

      // Act & Assert
      const response = await request(app.getHttpServer())
        .get(`/action-types/habit/${mockHabitId}`)
        .expect(200);

      expect(response.body.data).toHaveLength(1);
      expect(response.body.data[0].habitId).toBe(mockHabitId);
      expect(mockActionTypesService.findByHabitId).toHaveBeenCalledWith(
        mockHabitId,
        { page: 1, limit: 10 },
        undefined
      );
    });

    it('should validate habitId parameter', async () => {
      // Act & Assert
      await request(app.getHttpServer()).get('/action-types/habit/invalid-uuid').expect(400);
    });

    it('should handle pagination and filters for habit-specific query', async () => {
      // Arrange
      const mockResponse = new PaginatedResponseDto([], 0, 2, 5, 0);
      mockActionTypesService.findByHabitId.mockResolvedValue(mockResponse);

      // Act & Assert
      await request(app.getHttpServer())
        .get(`/action-types/habit/${mockHabitId}`)
        .query({ page: '2', limit: '5', hasActions: 'true' })
        .expect(200);

      expect(mockActionTypesService.findByHabitId).toHaveBeenCalledWith(
        mockHabitId,
        { page: 2, limit: 5 },
        { hasActions: true }
      );
    });
  });

  describe('GET /action-types/:id', () => {
    it('should return action type when found', async () => {
      // Arrange
      const expectedResponse = createMockActionTypeResponse();
      mockActionTypesService.findOne.mockResolvedValue(expectedResponse);

      // Act & Assert
      const response = await request(app.getHttpServer())
        .get(`/action-types/${mockActionTypeId}`)
        .expect(200);

      expect(response.body).toEqual(expectedResponse);
      expect(mockActionTypesService.findOne).toHaveBeenCalledWith(mockActionTypeId);
    });

    it('should return 404 when action type not found', async () => {
      // Arrange
      const notFoundError = new NotFoundError('ActionType', mockActionTypeId);
      mockActionTypesService.findOne.mockRejectedValue(notFoundError);

      // Act & Assert
      await request(app.getHttpServer()).get(`/action-types/${mockActionTypeId}`).expect(404);
    });

    it('should validate UUID parameter', async () => {
      // Act & Assert
      await request(app.getHttpServer()).get('/action-types/invalid-uuid').expect(400);
    });
  });

  describe('PATCH /action-types/:id', () => {
    const updateActionTypeDto = {
      name: 'Updated Push-ups',
    };

    it('should update action type successfully', async () => {
      // Arrange
      const expectedResponse = createMockActionTypeResponse({
        name: updateActionTypeDto.name,
        updatedAt: new Date(),
      });
      mockActionTypesService.update.mockResolvedValue(expectedResponse);

      // Act & Assert
      const response = await request(app.getHttpServer())
        .patch(`/action-types/${mockActionTypeId}`)
        .send(updateActionTypeDto)
        .expect(200);

      expect(response.body.name).toBe(updateActionTypeDto.name);
      expect(mockActionTypesService.update).toHaveBeenCalledWith(
        mockActionTypeId,
        updateActionTypeDto,
        undefined
      );
    });

    it('should update action type with new logo', async () => {
      // Arrange
      const newLogo = 'https://example.com/new-logo.png';
      const expectedResponse = createMockActionTypeResponse({
        logo: newLogo,
        updatedAt: new Date(),
      });
      mockActionTypesService.update.mockResolvedValue(expectedResponse);

      // Act & Assert
      const response = await request(app.getHttpServer())
        .patch(`/action-types/${mockActionTypeId}`)
        .attach('logo', createMockFile().buffer, 'new-logo.png')
        .expect(200);

      expect(mockActionTypesService.update).toHaveBeenCalledWith(
        mockActionTypeId,
        {},
        expect.objectContaining({
          originalname: 'new-logo.png',
          mimetype: 'image/png',
        })
      );
    });

    it('should update both name and logo', async () => {
      // Arrange
      const expectedResponse = createMockActionTypeResponse({
        name: updateActionTypeDto.name,
        logo: 'https://example.com/new-logo.png',
        updatedAt: new Date(),
      });
      mockActionTypesService.update.mockResolvedValue(expectedResponse);

      // Act & Assert
      await request(app.getHttpServer())
        .patch(`/action-types/${mockActionTypeId}`)
        .field('name', updateActionTypeDto.name)
        .attach('logo', createMockFile().buffer, 'new-logo.png')
        .expect(200);

      expect(mockActionTypesService.update).toHaveBeenCalledWith(
        mockActionTypeId,
        updateActionTypeDto,
        expect.objectContaining({
          originalname: 'new-logo.png',
        })
      );
    });

    it('should return 404 when action type not found', async () => {
      // Arrange
      const notFoundError = new NotFoundError('ActionType', mockActionTypeId);
      mockActionTypesService.update.mockRejectedValue(notFoundError);

      // Act & Assert
      await request(app.getHttpServer())
        .patch(`/action-types/${mockActionTypeId}`)
        .send(updateActionTypeDto)
        .expect(404);
    });

    it('should return 409 when name conflict occurs', async () => {
      // Arrange
      const conflictError = new ConflictError(
        `ActionType with name '${updateActionTypeDto.name}' already exists for this habit`
      );
      mockActionTypesService.update.mockRejectedValue(conflictError);

      // Act & Assert
      await request(app.getHttpServer())
        .patch(`/action-types/${mockActionTypeId}`)
        .send(updateActionTypeDto)
        .expect(409);
    });

    it('should validate update data', async () => {
      // Act & Assert
      await request(app.getHttpServer())
        .patch(`/action-types/${mockActionTypeId}`)
        .send({ name: '' }) // Invalid empty name
        .expect(400);

      await request(app.getHttpServer())
        .patch(`/action-types/${mockActionTypeId}`)
        .send({ name: 'A'.repeat(101) }) // Too long name
        .expect(400);
    });

    it('should validate UUID parameter', async () => {
      // Act & Assert
      await request(app.getHttpServer())
        .patch('/action-types/invalid-uuid')
        .send(updateActionTypeDto)
        .expect(400);
    });

    it('should handle empty update request', async () => {
      // Arrange
      const expectedResponse = createMockActionTypeResponse();
      mockActionTypesService.update.mockResolvedValue(expectedResponse);

      // Act & Assert
      await request(app.getHttpServer())
        .patch(`/action-types/${mockActionTypeId}`)
        .send({}) // Empty update
        .expect(200);

      expect(mockActionTypesService.update).toHaveBeenCalledWith(mockActionTypeId, {}, undefined);
    });
  });

  describe('DELETE /action-types/:id', () => {
    it('should delete action type successfully', async () => {
      // Arrange
      mockActionTypesService.remove.mockResolvedValue(undefined);

      // Act & Assert
      await request(app.getHttpServer()).delete(`/action-types/${mockActionTypeId}`).expect(204);

      expect(mockActionTypesService.remove).toHaveBeenCalledWith(mockActionTypeId);
    });

    it('should return 404 when action type not found', async () => {
      // Arrange
      const notFoundError = new NotFoundError('ActionType', mockActionTypeId);
      mockActionTypesService.remove.mockRejectedValue(notFoundError);

      // Act & Assert
      await request(app.getHttpServer()).delete(`/action-types/${mockActionTypeId}`).expect(404);
    });

    it('should validate UUID parameter', async () => {
      // Act & Assert
      await request(app.getHttpServer()).delete('/action-types/invalid-uuid').expect(400);
    });
  });

  describe('GET /action-types/most-active', () => {
    it('should return most active action types', async () => {
      // Arrange
      const mockActiveTypes = [
        createMockActionTypeResponse({ totalActionsCount: 50 }),
        createMockActionTypeResponse({ totalActionsCount: 30 }),
      ];
      mockActionTypesService.findMostActive.mockResolvedValue(mockActiveTypes);

      // Act & Assert
      const response = await request(app.getHttpServer())
        .get('/action-types/most-active')
        .query({ limit: '5' })
        .expect(200);

      expect(response.body).toHaveLength(2);
      expect(response.body[0].totalActionsCount).toBe(50);
      expect(mockActionTypesService.findMostActive).toHaveBeenCalledWith(5);
    });

    it('should use default limit when not provided', async () => {
      // Arrange
      mockActionTypesService.findMostActive.mockResolvedValue([]);

      // Act & Assert
      await request(app.getHttpServer()).get('/action-types/most-active').expect(200);

      expect(mockActionTypesService.findMostActive).toHaveBeenCalledWith(10);
    });

    it('should validate limit parameter', async () => {
      // Act & Assert
      await request(app.getHttpServer())
        .get('/action-types/most-active')
        .query({ limit: '0' })
        .expect(400);

      await request(app.getHttpServer())
        .get('/action-types/most-active')
        .query({ limit: '101' })
        .expect(400);
    });
  });

  describe('GET /action-types/recently-active', () => {
    it('should return recently active action types', async () => {
      // Arrange
      const mockRecentTypes = [createMockActionTypeResponse({ lastActionDate: new Date() })];
      mockActionTypesService.findRecentlyActive.mockResolvedValue(mockRecentTypes);

      // Act & Assert
      const response = await request(app.getHttpServer())
        .get('/action-types/recently-active')
        .query({ days: '7', limit: '10' })
        .expect(200);

      expect(response.body).toHaveLength(1);
      expect(mockActionTypesService.findRecentlyActive).toHaveBeenCalledWith(7, 10);
    });

    it('should use default values when parameters not provided', async () => {
      // Arrange
      mockActionTypesService.findRecentlyActive.mockResolvedValue([]);

      // Act & Assert
      await request(app.getHttpServer()).get('/action-types/recently-active').expect(200);

      expect(mockActionTypesService.findRecentlyActive).toHaveBeenCalledWith(7, 10);
    });

    it('should validate query parameters', async () => {
      // Act & Assert
      await request(app.getHttpServer())
        .get('/action-types/recently-active')
        .query({ days: '0', limit: '10' })
        .expect(400);

      await request(app.getHttpServer())
        .get('/action-types/recently-active')
        .query({ days: '7', limit: '0' })
        .expect(400);
    });
  });

  describe('GET /action-types/stats/habit/:habitId', () => {
    it('should return statistics for habit', async () => {
      // Arrange
      const mockStats: ActionTypeStats = {
        totalActionTypes: 5,
        activeActionTypes: 4,
        totalActions: 100,
        averageActionsPerType: 20,
        mostActiveActionType: {
          id: mockActionTypeId,
          name: mockActionTypeName,
          totalActionsCount: 50,
        },
        leastActiveActionType: {
          id: mockActionTypeId,
          name: mockActionTypeName,
          totalActionsCount: 0,
        },
        recentlyActiveCount: 3,
      };
      mockActionTypesService.getStatsByHabitId.mockResolvedValue(mockStats);

      // Act & Assert
      const response = await request(app.getHttpServer())
        .get(`/action-types/stats/habit/${mockHabitId}`)
        .expect(200);

      expect(response.body).toEqual(mockStats);
      expect(mockActionTypesService.getStatsByHabitId).toHaveBeenCalledWith(mockHabitId);
    });

    it('should validate habitId parameter', async () => {
      // Act & Assert
      await request(app.getHttpServer()).get('/action-types/stats/habit/invalid-uuid').expect(400);
    });
  });

  describe('Error handling and middleware', () => {
    it('should handle internal server errors', async () => {
      // Arrange
      const internalError = new Error('Internal server error');
      mockActionTypesService.findAll.mockRejectedValue(internalError);

      // Act & Assert
      await request(app.getHttpServer()).get('/action-types').expect(500);
    });

    it('should handle malformed JSON in request body', async () => {
      // Act & Assert
      await request(app.getHttpServer())
        .patch(`/action-types/${mockActionTypeId}`)
        .set('Content-Type', 'application/json')
        .send('{"name": invalid json}')
        .expect(400);
    });

    it('should reject requests with oversized payloads', async () => {
      // Act & Assert
      const largeData = { name: 'A'.repeat(10000) }; // Very large name
      await request(app.getHttpServer())
        .patch(`/action-types/${mockActionTypeId}`)
        .send(largeData)
        .expect(400);
    });

    it('should handle CORS preflight requests', async () => {
      // Act & Assert
      await request(app.getHttpServer()).options('/action-types').expect(200);
    });

    it('should validate Content-Type for file uploads', async () => {
      // Act & Assert
      await request(app.getHttpServer())
        .post('/action-types')
        .field('name', mockActionTypeName)
        .field('habitId', mockHabitId)
        .attach('logo', Buffer.from('not an image'), 'file.txt')
        .expect(400);
    });
  });

  describe('API Documentation and OpenAPI', () => {
    it('should include appropriate Swagger decorators for all endpoints', () => {
      // This test verifies that the controller has proper API documentation
      // The actual implementation would check for @ApiOperation, @ApiResponse decorators
      expect(ActionTypesController).toBeDefined();
    });

    it('should define proper request DTO with domain fields only', () => {
      // CreateActionTypeDto should contain ONLY domain fields
      const createDto = {
        name: mockActionTypeName,
        habitId: mockHabitId,
      };

      // Verify DTO structure - should NOT have database-generated fields
      expect(createDto).toHaveProperty('name');
      expect(createDto).toHaveProperty('habitId');
      expect(createDto).not.toHaveProperty('id');
      expect(createDto).not.toHaveProperty('createdAt');
      expect(createDto).not.toHaveProperty('updatedAt');
      expect(createDto).not.toHaveProperty('totalActionsCount');
      expect(createDto).not.toHaveProperty('lastActionDate');
    });

    it('should define proper response schemas for OpenAPI generation', () => {
      // Response DTO includes complete entity with database-generated fields
      const mockResponse = createMockActionTypeResponse();
      expect(mockResponse).toHaveProperty('id');
      expect(mockResponse).toHaveProperty('name');
      expect(mockResponse).toHaveProperty('logo');
      expect(mockResponse).toHaveProperty('habitId');
      expect(mockResponse).toHaveProperty('totalActionsCount');
      expect(mockResponse).toHaveProperty('lastActionDate');
      expect(mockResponse).toHaveProperty('createdAt');
      expect(mockResponse).toHaveProperty('updatedAt');
    });
  });

  describe('Security and Authentication', () => {
    it('should require authentication for all protected endpoints', async () => {
      // Note: This test assumes authentication middleware will be added
      // Currently testing the controller logic without authentication

      // Act & Assert - All endpoints should be accessible for testing
      await request(app.getHttpServer()).get('/action-types').expect(200);
    });

    it('should sanitize file uploads to prevent malicious files', async () => {
      // Act & Assert
      const suspiciousFile = {
        fieldname: 'logo',
        originalname: '../../../etc/passwd',
        encoding: '7bit',
        mimetype: 'text/plain',
        size: 100,
        buffer: Buffer.from('malicious content'),
      };

      await request(app.getHttpServer())
        .post('/action-types')
        .field('name', mockActionTypeName)
        .field('habitId', mockHabitId)
        .attach('logo', suspiciousFile.buffer, suspiciousFile.originalname)
        .expect(400); // Should reject non-image files
    });

    it('should handle request rate limiting gracefully', async () => {
      // Note: This would test rate limiting middleware when implemented
      // Currently just verifying basic request handling

      const requests = Array(5)
        .fill(null)
        .map(() => request(app.getHttpServer()).get('/action-types'));

      const responses = await Promise.all(requests);
      responses.forEach(response => {
        expect([200, 429]).toContain(response.status);
      });
    });
  });
});
