"""add image column to book table

Revision ID: 223da5fda91f
Revises: 7def0068231c
Create Date: 2024-11-12 08:53:02.805286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '223da5fda91f'
down_revision: Union[str, None] = '7def0068231c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'image')
    # ### end Alembic commands ###
