"""add using voice column to reading_logs table

Revision ID: 23d9239d3078
Revises: 223da5fda91f
Create Date: 2024-11-14 08:44:40.692704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23d9239d3078'
down_revision: Union[str, None] = '223da5fda91f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading_logs', sa.Column('using_voice', sa.Boolean(), nullable=False))
    op.alter_column('reading_logs', 'number_of_characters_per_minute',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('reading_logs', 'number_of_breaths_per_minute',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reading_logs', 'number_of_breaths_per_minute',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('reading_logs', 'number_of_characters_per_minute',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('reading_logs', 'using_voice')
    # ### end Alembic commands ###
