"""add current_page column to book table

Revision ID: 7def0068231c
Revises: 38e52b360508
Create Date: 2024-11-09 08:59:02.614195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7def0068231c'
down_revision: Union[str, None] = '38e52b360508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('current_page', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'current_page')
    # ### end Alembic commands ###
